# Generated by Django 5.2.9 on 2025-12-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='excels/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Marca este Excel como el activo para consultas.')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='consulta.archivoexcel')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_columna', models.CharField(max_length=150)),
                ('visible', models.BooleanField(default=True)),
                ('es_dni', models.BooleanField(default=False)),
                ('es_fecha_ingreso', models.BooleanField(default=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='consulta.archivoexcel')),
            ],
            options={
                'ordering': ['nombre_columna'],
                'unique_together': {('archivo', 'nombre_columna')},
            },
        ),
    ]
